In [2]:
import numpy as np
import os
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from tqdm import tqdm
import matplotlib.pyplot as plt
from h5py import File
from scripts.dataset import Dataset
from scripts.model import STRCA, FBTRCA
from scipy.linalg import eigh

In [2]:
import numpy as np
from tqdm import tqdm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

if __name__=="__main__":
    Fs = 256
    Co = 11
    num_fold = 5
    num_subj = 15
    max_freq = 10
    step_bank= 2
    frange = np.arange(step_bank,max_freq+1,step_bank)
    channels = (np.int64([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])-1).tolist()
    num_bank = int(max_freq/step_bank)
    t  = [0, 2]
    result = np.zeros([num_subj, num_fold, 4])

    for sub in range(num_subj):
        dataset = Dataset(num_class=7, path='Dataset/OData/Dataset I/', channel=channels)
        dataset.load_data(sub, None)
        dataset.divide_data(num_fold)
        dataset.filter_data(fs=Fs, frange=frange, order=8, btype='lowpass')
        for fold in tqdm(range(num_fold), desc=f'Sub{sub}:'):
            train_set, train_label, test_set, test_label = dataset.retreive_data(
                class_index=[0, 1, 2, 3, 4, 5, 6], fold_index=fold, filter_index=np.arange(len(frange)) + 1)
            train_set = train_set[:, :, int(t[0] * Fs):int(t[1] * Fs), :]
            test_set = test_set[:, :, int(t[0] * Fs):int(t[1] * Fs), :]

            train_data = train_set.reshape((len(train_label), -1))
            test_data = test_set.reshape((len(test_label), -1))
            svm = SVC(kernel='rbf')
            svm.fit(train_data, train_label)
            result[sub, fold, 0] = svm.score(test_data, test_label)

Sub14:: 100%|██████████| 5/5 [00:12<00:00,  2.41s/it]


In [3]:
np.mean(result,axis=(0,1))

array([0.25742184, 0.        , 0.        , 0.        ])

In [4]:
import numpy as np
from tqdm import tqdm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

if __name__=="__main__":
    Fs = 256
    Co = 21
    num_fold = 5
    num_subj = 15
    max_freq = 10
    step_bank= 2
    frange = np.arange(step_bank,max_freq+1,step_bank)
    channels = (np.int64([1,3,5,12,15,18,20,21,24,25,29,30,31,35,36,39,40,45,55,57,59])-1).tolist()
    num_bank = int(max_freq/step_bank)
    t  = [0, 2]
    result = np.zeros([num_subj, num_fold, 4])

    for sub in range(num_subj):
        dataset = Dataset(num_class=7, path='Dataset/OData/Dataset I/', channel=channels)
        dataset.load_data(sub, None)
        dataset.divide_data(num_fold)
        dataset.filter_data(fs=Fs, frange=frange, order=8, btype='lowpass')
        for fold in tqdm(range(num_fold), desc=f'Sub{sub}:'):
            train_set, train_label, test_set, test_label = dataset.retreive_data(
                class_index=[0, 1, 2, 3, 4, 5, 6], fold_index=fold, filter_index=np.arange(len(frange)) + 1)
            train_set = train_set[:, :, int(t[0] * Fs):int(t[1] * Fs), :]
            test_set = test_set[:, :, int(t[0] * Fs):int(t[1] * Fs), :]

            train_data = train_set.reshape((len(train_label), -1))
            test_data = test_set.reshape((len(test_label), -1))
            svm = SVC(kernel='rbf')
            svm.fit(train_data, train_label)
            result[sub, fold, 0] = svm.score(test_data, test_label)

Sub14:: 100%|██████████| 5/5 [00:25<00:00,  5.14s/it]


In [5]:
np.mean(result,axis=(0,1))

array([0.38404499, 0.        , 0.        , 0.        ])

In [3]:
import numpy as np
from tqdm import tqdm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

if __name__=="__main__":
    Fs = 256
    Co = 31
    num_fold = 5
    num_subj = 15
    max_freq = 10
    step_bank= 2
    frange = np.arange(step_bank,max_freq+1,step_bank)
    channels = (np.int64([1,3,5,6,11,12,13,15,17,18,20,21,24,25,27,29,30,31,33,35,36,39,40,42,43,45,47,48,55,57,59])-1).tolist()
    num_bank = int(max_freq/step_bank)
    t  = [0, 2]
    result = np.zeros([num_subj, num_fold, 4])

    for sub in range(num_subj):
        dataset = Dataset(num_class=7, path='Dataset/OData/Dataset I/', channel=channels)
        dataset.load_data(sub, None)
        dataset.divide_data(num_fold)
        dataset.filter_data(fs=Fs, frange=frange, order=8, btype='lowpass')
        for fold in tqdm(range(num_fold), desc=f'Sub{sub}:'):
            train_set, train_label, test_set, test_label = dataset.retreive_data(
                class_index=[0, 1, 2, 3, 4, 5, 6], fold_index=fold, filter_index=np.arange(len(frange)) + 1)
            train_set = train_set[:, :, int(t[0] * Fs):int(t[1] * Fs), :]
            test_set = test_set[:, :, int(t[0] * Fs):int(t[1] * Fs), :]

            train_data = train_set.reshape((len(train_label), -1))
            test_data = test_set.reshape((len(test_label), -1))
            svm = SVC(kernel='rbf')
            svm.fit(train_data, train_label)
            result[sub, fold, 0] = svm.score(test_data, test_label)

Sub14:: 100%|██████████| 5/5 [00:38<00:00,  7.78s/it]


In [4]:
np.mean(result,axis=(0,1))

array([0.39973675, 0.        , 0.        , 0.        ])

In [5]:
import numpy as np
from tqdm import tqdm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

if __name__=="__main__":
    Fs = 256
    Co = 41
    num_fold = 5
    num_subj = 15
    max_freq = 10
    step_bank= 2
    frange = np.arange(step_bank,max_freq+1,step_bank)
    channels = (np.int64([1,3,5,6,7,10,11,12,13,15,17,18,19,20,21,24,25,26,27,28,29,30,31,32,33,35,36,39,40,42,43,45,47,48,49,50,53,54,55,57,59])-1).tolist()
    num_bank = int(max_freq/step_bank)
    t  = [0, 2]
    result = np.zeros([num_subj, num_fold, 4])

    for sub in range(num_subj):
        dataset = Dataset(num_class=7, path='Dataset/OData/Dataset I/', channel=channels)
        dataset.load_data(sub, None)
        dataset.divide_data(num_fold)
        dataset.filter_data(fs=Fs, frange=frange, order=8, btype='lowpass')
        for fold in tqdm(range(num_fold), desc=f'Sub{sub}:'):
            train_set, train_label, test_set, test_label = dataset.retreive_data(
                class_index=[0, 1, 2, 3, 4, 5, 6], fold_index=fold, filter_index=np.arange(len(frange)) + 1)
            train_set = train_set[:, :, int(t[0] * Fs):int(t[1] * Fs), :]
            test_set = test_set[:, :, int(t[0] * Fs):int(t[1] * Fs), :]

            train_data = train_set.reshape((len(train_label), -1))
            test_data = test_set.reshape((len(test_label), -1))
            svm = SVC(kernel='rbf')
            svm.fit(train_data, train_label)
            result[sub, fold, 0] = svm.score(test_data, test_label)

Sub14:: 100%|██████████| 5/5 [00:52<00:00, 10.56s/it]


In [6]:
np.mean(result,axis=(0,1))

array([0.39759639, 0.        , 0.        , 0.        ])

In [7]:
import numpy as np
from tqdm import tqdm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

if __name__=="__main__":
    Fs = 256
    Co = 51
    num_fold = 5
    num_subj = 15
    max_freq = 10
    step_bank= 2
    frange = np.arange(step_bank,max_freq+1,step_bank)
    channels = (np.int64([1,2,3,4,5,6,7,10,11,12,13,14,15,16,17,18,19,20,21,24,25,26,27,28,29,30,31,32,33,34,35,36,39,40,41,42,43,44,45,46,47,48,49,50,53,54,55,56,57,58,59])-1).tolist()
    num_bank = int(max_freq/step_bank)
    t  = [0, 2]
    result = np.zeros([num_subj, num_fold, 4])

    for sub in range(num_subj):
        dataset = Dataset(num_class=7, path='Dataset/OData/Dataset I/', channel=channels)
        dataset.load_data(sub, None)
        dataset.divide_data(num_fold)
        dataset.filter_data(fs=Fs, frange=frange, order=8, btype='lowpass')
        for fold in tqdm(range(num_fold), desc=f'Sub{sub}:'):
            train_set, train_label, test_set, test_label = dataset.retreive_data(
                class_index=[0, 1, 2, 3, 4, 5, 6], fold_index=fold, filter_index=np.arange(len(frange)) + 1)
            train_set = train_set[:, :, int(t[0] * Fs):int(t[1] * Fs), :]
            test_set = test_set[:, :, int(t[0] * Fs):int(t[1] * Fs), :]

            train_data = train_set.reshape((len(train_label), -1))
            test_data = test_set.reshape((len(test_label), -1))
            svm = SVC(kernel='rbf')
            svm.fit(train_data, train_label)
            result[sub, fold, 0] = svm.score(test_data, test_label)

Sub14:: 100%|██████████| 5/5 [01:24<00:00, 16.94s/it]


In [8]:
np.mean(result,axis=(0,1))

array([0.4014678, 0.       , 0.       , 0.       ])

In [9]:
import numpy as np
from tqdm import tqdm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

if __name__=="__main__":
    Fs = 256
    Co = 61
    num_fold = 5
    num_subj = 15
    max_freq = 10
    step_bank= 2
    frange = np.arange(step_bank,max_freq+1,step_bank)
    channels = (np.int64([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61])-1).tolist()
    num_bank = int(max_freq/step_bank)
    t  = [0, 2]
    result = np.zeros([num_subj, num_fold, 4])

    for sub in range(num_subj):
        dataset = Dataset(num_class=7, path='Dataset/OData/Dataset I/', channel=channels)
        dataset.load_data(sub, None)
        dataset.divide_data(num_fold)
        dataset.filter_data(fs=Fs, frange=frange, order=8, btype='lowpass')
        for fold in tqdm(range(num_fold), desc=f'Sub{sub}:'):
            train_set, train_label, test_set, test_label = dataset.retreive_data(
                class_index=[0, 1, 2, 3, 4, 5, 6], fold_index=fold, filter_index=np.arange(len(frange)) + 1)
            train_set = train_set[:, :, int(t[0] * Fs):int(t[1] * Fs), :]
            test_set = test_set[:, :, int(t[0] * Fs):int(t[1] * Fs), :]

            train_data = train_set.reshape((len(train_label), -1))
            test_data = test_set.reshape((len(test_label), -1))
            svm = SVC(kernel='rbf')
            svm.fit(train_data, train_label)
            result[sub, fold, 0] = svm.score(test_data, test_label)

Sub14:: 100%|██████████| 5/5 [01:40<00:00, 20.04s/it]


In [10]:
np.mean(result,axis=(0,1))

array([0.40589993, 0.        , 0.        , 0.        ])